### ISSUE TITLE
500 is not a valid SSR component in Sapper

### ISSUE THREAD

**Issue by GiorgosK** [shiryel/saos#1]
This is a very nice component.
I have setup a page exactly like the demo https://github.com/shiryel/saos/blob/master/demo/src/Animations.svelte
in Sapper and it works nice but I get the following error once in a while

>500
<Saos> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
> Error: <Saos> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validate_component (/home/web/svelte-sapper-experiments/__sapper__/dev/server/server.js:291:15)
    at /home/web/svelte-sapper-experiments/__sapper__/dev/server/server.js:2163:48
    at Object.$$render (/home/web/svelte-sapper-experiments/__sapper__/dev/server/server.js:309:22)
    at Object.default (/home/web/svelte-sapper-experiments/__sapper__/dev/server/server.js:2982:86)
    at Object.default (/home/web/svelte-sapper-experiments/__sapper__/dev/server/server.js:2728:84)
    at /home/web/svelte-sapper-experiments/__sapper__/dev/server/server.js:2691:46
    at Object.$$render (/home/web/svelte-sapper-experiments/__sapper__/dev/server/server.js:309:22)
    at /home/web/svelte-sapper-experiments/__sapper__/dev/server/server.js:2727:58
    at Object.$$render (/home/web/svelte-sapper-experiments/__sapper__/dev/server/server.js:309:22)
    at /home/web/svelte-sapper-experiments/__sapper__/dev/server/server.js:2979:40

Also some times when i navigate to another route I still see the contents of this Animation page and I usually need to refresh the page and navigate back and forth before this page runs again.

I have seen https://github.com/sveltejs/sapper/issues/774 that might help.

**Comment by shiryel** [comment]
@GiorgosK Thanks for opening the issue, I think I fixed it, just a miss-configuration. Please tell me if its now working for you :smile: 

PS: Sorry for replying so late, I messed up with my github notifications

**Comment by GiorgosK** [comment]
@shiryel no problem, now it works great

**Comment by GiorgosK** [comment]
Sorry it seems to still be there when making any change to a .svelte that includes `saos` and than sapper dev rebuilds and refreshes the browser

> <Saos> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
> Error: <Saos> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validate_component (/home/web/svelte-sapper-experiments/node_modules/svelte/internal/index.mjs:1342:18)
    at /home/web/svelte-sapper-experiments/__sapper__/dev/server/server.js:2465:48
    at Object.$$render (/home/web/svelte-sapper-experiments/node_modules/svelte/internal/index.mjs:1365:23)
    at Object.default (/home/web/svelte-sapper-experiments/src/node_modules/@sapper/internal/App.svelte:24:50)
    at Object.default (/home/web/svelte-sapper-experiments/__sapper__/dev/server/server.js:3068:85)
    at /home/web/svelte-sapper-experiments/__sapper__/dev/server/server.js:3029:46
    at Object.$$render (/home/web/svelte-sapper-experiments/node_modules/svelte/internal/index.mjs:1365:23)
    at /home/web/svelte-sapper-experiments/src/routes/_layout.svelte:33:26
    at Object.$$render (/home/web/svelte-sapper-experiments/node_modules/svelte/internal/index.mjs:1365:23)
    at /home/web/svelte-sapper-experiments/src/node_modules/@sapper/internal/App.svelte:20:18

**Comment by shiryel** [comment]
@GiorgosK I don't know if I'm missing some configuration to make the sapper SSR work, but installing as a dev dependency solves this problem for me

**Comment by shiryel** [comment]
I noticed that in some other packages, when they have this problem and can't be used as a dev dependency, they make the import like this: `import Saos from 'saos/src/Saos.svelte';` and that worked for me too

**Comment by GiorgosK** [comment]
@shiryel yes adding saos as dev dependency solves the previous mentioned problems\
thanks
